### ISSUE TITLE
Handling changes with the sympasoap implementation

### ISSUE THREAD

**Issue by evoltech** [djberg96/mail-sympa#3]
I am working with sympa-6.1.6 right now using this library and test suite to test out some features I am adding to the sympasoap and I am realizing that the test cases are going to have different results on different sympa versions.  It would be nice to have the testcases all pass with a default installation, but they may fail as sympasoap changes.

I propose that branches are created for future releases that succeed with different versions of sympa.

**Comment by djberg96** [comment]
If the API hasn't changed, but only the results of various calls, then it's the tests that need to be modified to check for the Sympa version.

But we need to know what those differences are.

**Comment by djberg96** [comment]
Super stale, closing.
